version: '3.8'

services:
  server:
    build:
      dockerfile: DockerFile.local
      context: ./
    container_name: template
    restart: always
#    depends_on:
#      - mongo
#      - mysql
#      - redis
#      - rabbitmq
#      - opensearch
    ports:
      - '80:80'
    volumes:
      - ./docker/server/dumps:/dumps
      - ./docker/server/logs:/logs
    environment:
      GRADLE_OPTS: "-Xmx1g"
      TZ: Asia/Seoul

#  mongo:
#    container_name: template_mongo_db
#    image: mongo:4.2.24
#    restart: always
#    ports:
#      - '27017:27017'
#    volumes:
#      - ./docker/mongo/db:/data/db
#      - ./docker/mongo/initdb/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
#      TZ: Asia/Seoul

#  mysql:
#    container_name: template_mysql_db
#    image: mysql:8.0.23
#    platform: linux/amd64
#    ports:
#      - '3306:3306'
#    restart: always
#    volumes:
#      - ./docker/mysql/db:/var/lib/mysql
#      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
#    environment:
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      TZ: Asia/Seoul

#  redis:
#    image: redis:latest
#    container_name: template_redis
#    restart: always
#    ports:
#      - '6379:6379'
#    volumes:
#      - ./docker/redis/data:/data
#      - ./docker/redis/conf/redis.conf:/usr/local/conf/redis.conf
#    labels:
#      - "name=redis"
#      - "mode=standalone"
#    command:
#      redis-server /usr/local/conf/redis.conf

#  rabbitmq:
#    image: rabbitmq:3.8-management
#    container_name: template_rabbitmq
#    volumes:
#      - ./docker/rabbitmq/conf/:/etc/rabbitmq/
#      - ./docker/rabbitmq/lib/:/var/lib/rabbitmq/
#      - ./docker/rabbitmq/log/:/var/log/rabbitmq/
#    ports:
#      - '5672:5672'
#      - '15672:15672'
#    environment:
#      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
#      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
#      TZ: Asia/Seoul

#  opensearch:
#    image: opensearchproject/opensearch:latest
#    container_name: template_opensearch
#    environment:
#      - discovery.type=single-node
#      - bootstrap.memory_lock=true
#      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "DISABLE_SECURITY_PLUGIN=true"
#    ports:
#      - "9200:9200"
#      - "9600:9600"
#    volumes:
#      - ./docker/opensearch/data:/usr/share/opensearch/data
